### ISSUE TITLE
Change lidar to single layer

### ISSUE THREAD

**Issue by simonbogh** [Nitrow/P9-SLAM-RL#2]
Change the lidar in .sdf to only have one layer down from 16. Only one layer is probably needed and the simulation may run faster.

```xml
<vertical>
    <samples>1</samples>
    <resolution>1</resolution>
    <min_angle>0</min_angle>
    <max_angle>0</max_angle>
</vertical>
```

**Comment by Nitrow** [comment]
Changed it to the suggested. At first it didn't work, but changed to ogre2 and it worked!
